CREATE TABLE "Element_Properties" (
    "chemical_element" varchar,
    "atomic_mass" float,
    "poissons_ratio" float,
    "atomic_radius" float,
    "electrical_resistivity" float,
    "molar_volume" float ,
    "thermal_conductivity" float,
    "bulk_modulus" float,
    "youngs_modulus" float,
    "periodic_group" int,
    "is_noble_gas" bool,
    "is_transition_metal" bool,
    "is_post_transition_metal" bool ,
    "is_rare_earth_metal" bool,
    "is_metalloid" bool,
    "is_alkali" bool,
    "is_alkaline" bool,
    "is_halogen" bool,
    "is_lanthanoid" bool,
    "is_actinoid" bool,
    "van_der_waals_radius" float,
    "velocity_of_sound" float,
    "critical_temperature" float,
    "superconduction_temperature" float,
    "average_cationic_radius" float,
    "average_anionic_radius" float,
    "ionic_radii" float,
    "boiling_point" float,
    "vickers_hardness" float,
    "average_ionic_radius" float,
    "melting_point" float,
    "rigidity_modulus" float,
    "Z" int,
    "atomic_number" int,
    "density_of_solid" float,
    "coefficient_of_linear_thermal_expansion" float
);

CREATE TABLE "Materials_Properties" (
    "mp_id" varchar   NOT NULL,
    "Formula" varchar   NOT NULL,
    "IPF" float   NOT NULL,
    "Density" float   NOT NULL,
    "E_above_Hull" float   NOT NULL,
    "G_VRH" float   NOT NULL,
    "K_VRH" float   NOT NULL,
    "Elastic_Anisotropy" float   NOT NULL,
    "poisson_ratio" float   NOT NULL,
    "Y_Modulus" float   NOT NULL,
);

CREATE TABLE "Materials_Composition" (
    "mp_id" varchar   NOT NULL,
    "H" float   NOT NULL,
    "He" float   NOT NULL,
    "Li" float   NOT NULL,
    "Be" float   NOT NULL,
    "B" float   NOT NULL,
    "C" float   NOT NULL,
    "N" float   NOT NULL,
    "O" float   NOT NULL,
    "F" float   NOT NULL,
    "Ne" float   NOT NULL,
    "Na" float   NOT NULL,
    "Mg" float   NOT NULL,
    "Al" float   NOT NULL,
    "Si" float   NOT NULL,
    "P" float   NOT NULL,
    "S" float   NOT NULL,
    "Cl" float   NOT NULL,
    "Ar" float   NOT NULL,
    "K" float   NOT NULL,
    "Ca" float   NOT NULL,
    "Sc" float   NOT NULL,
    "Ti" float   NOT NULL,
    "V" float   NOT NULL,
    "Cr" float   NOT NULL,
    "Mn" float   NOT NULL,
    "Fe" float   NOT NULL,
    "Co" float   NOT NULL,
    "Ni" float   NOT NULL,
    "Cu" float   NOT NULL,
    "Zn" float   NOT NULL,
    "Ga" float   NOT NULL,
    "Ge" float   NOT NULL,
    "As" float   NOT NULL,
    "Se" float   NOT NULL,
    "Br" float   NOT NULL,
    "Kr" float   NOT NULL,
    "Rb" float   NOT NULL,
    "Sr" float   NOT NULL,
    "Y" float   NOT NULL,
    "Zr" float   NOT NULL,
    "Nb" float   NOT NULL,
    "Mo" float   NOT NULL,
    "Tc" float   NOT NULL,
    "Ru" float   NOT NULL,
    "Rh" float   NOT NULL,
    "Pd" float   NOT NULL,
    "Ag" float   NOT NULL,
    "Cd" float   NOT NULL,
    "In" float   NOT NULL,
    "Sn" float   NOT NULL,
    "Sb" float   NOT NULL,
    "Te" float   NOT NULL,
    "I" float   NOT NULL,
    "Xe" float   NOT NULL,
    "Cs" float   NOT NULL,
    "Ba" float   NOT NULL,
    "La" float   NOT NULL,
    "Ce" float   NOT NULL,
    "Pr" float   NOT NULL,
    "Nd" float   NOT NULL,
    "Pm" float   NOT NULL,
    "Sm" float   NOT NULL,
    "Eu" float   NOT NULL,
    "Gd" float   NOT NULL,
    "Tb" float   NOT NULL,
    "Dy" float   NOT NULL,
    "Ho" float   NOT NULL,
    "Er" float   NOT NULL,
    "Tm" float   NOT NULL,
    "Yb" float   NOT NULL,
    "Lu" float   NOT NULL,
    "Hf" float   NOT NULL,
    "Ta" float   NOT NULL,
    "W" float   NOT NULL,
    "Re" float   NOT NULL,
    "Os" float   NOT NULL,
    "Ir" float   NOT NULL,
    "Pt" float   NOT NULL,
    "Au" float   NOT NULL,
    "Hg" float   NOT NULL,
    "Tl" float   NOT NULL,
    "Pb" float   NOT NULL,
    "Bi" float   NOT NULL,
    "Po" float   NOT NULL,
    "At" float   NOT NULL,
    "Rn" float   NOT NULL,
    "Fr" float   NOT NULL,
    "Ra" float   NOT NULL,
    "Ac" float   NOT NULL,
    "Th" float   NOT NULL,
    "Pa" float   NOT NULL,
    "U" float   NOT NULL,
    "Np" float   NOT NULL,
    "Pu" float   NOT NULL,
    "Am" float   NOT NULL,
    "Cm" float   NOT NULL,
    "Bk" float   NOT NULL,
    "Cf" float   NOT NULL,
    "Es" float   NOT NULL,
    "Fm" float   NOT NULL,
    "Md" float   NOT NULL,
    "No" float   NOT NULL,
    "Lr" float   NOT NULL,
);